### PR TITLE
added serializer for django rest framework

### PR DESCRIPTION
**Pull request by b0lle**
this is how I use your package with django rest framework. Hope this helps someone to avoid create them hisself. Thanks for your package!

### CODE REVIEW

**Comment by sergioteula** [comment]
Hello, thanks a lot for sharing your code. I'm not very familiar with django, could you please explain a bit how this works and how is integrated with the API? It would be more convenient for me to understand it before merging to master and adding it to documentation. Thanks again!

**Comment by YPCrumble** [comment]
This is cool! What would be awesome is to also have a fixture for the AMZN response that we could use for testing this and other parts of this repo per #15. @b0lle if you have this in your serializers any way you could use [Django fixtures](https://docs.djangoproject.com/en/dev/howto/initial-data/) to create a JSON fixture file from one of your model instances?

**Comment by b0lle** [comment]
I can update the Readme file to give an example how to use serializers.

I can also provide a JSON file with serialized data. I would avoid a Django fixture because my database models do not store all fields available through this API. In my opinion there should be a test folder with an extra data folder. This is what I can create „tests/data“. Any other suggestions?

**Comment by sergioteula** [comment]
Thanks a lot for your help, that would be perfect. Once ready I will review and merge.

**Comment by b0lle** [comment]
The updated are pushed. I changed to location of the 'serializers' folder to be a part of the installed package. Hope thats in your mind.

**Pull request merged**
